# Generated by Django 2.2.5 on 2019-09-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='extra_field_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='extra_field_heading',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
