# Generated by Django 2.2.5 on 2019-09-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutImage', models.ImageField(upload_to='about/images')),
                ('section_heading_one', models.CharField(blank=True, max_length=200, null=True)),
                ('section_description_one', models.TextField(blank=True, null=True)),
                ('section_heading_two', models.CharField(blank=True, max_length=200, null=True)),
                ('section_description_two', models.TextField(blank=True, null=True)),
                ('section_heading_three', models.CharField(blank=True, max_length=200, null=True)),
                ('section_description_three', models.TextField(blank=True, null=True)),
                ('section_heading_four', models.CharField(blank=True, max_length=200, null=True)),
                ('section_description_four', models.TextField(blank=True, null=True)),
                ('section_heading_five', models.CharField(blank=True, max_length=200, null=True)),
                ('section_description_five', models.TextField(blank=True, null=True)),
                ('section_heading_six', models.CharField(blank=True, max_length=200, null=True)),
                ('section_description_six', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
