# Generated by Django 2.2.5 on 2019-09-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='avoutVideo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
