# Generated by Django 2.2.5 on 2019-09-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
