# Generated by Django 2.2.5 on 2019-09-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_slider_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
